version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bullmq-network
    environment:
      - REDIS_PASSWORD=myStrongPassword
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

networks:
  bullmq-network:
    driver: bridge


